common_packages:
  - acl
  - bison
  - chrony
  - firewalld
  - curl
  - dbus
  - flex
  - gcc
  - logrotate
  - lsof
  - lvm2
  - lsscsi
  - net-tools
  - openssh-server
  - parted
  - perl
  - python3-pip
  - rsync
  - rsyslog
  - sshpass
  - tar
  - unzip
  - util-linux
  - wget
  - zip
redhat_packages:
  - bzip2-devel
  - cronie
  - dbus-tools
  - gdbm-devel
  - grubby
  - initscripts
  - ncurses-devel
  - NetworkManager-initscripts-updown
  - openssl-devel
  - pcre-devel
  - python3-devel
  - readline-devel
  - sqlite-devel
  - systemd-devel
  - tk-devel
  - xz-devel
  - zlib-devel
  - iscsi-initiator-utils
  - firewalld
  - libffi-devel
  - libicu-devel
  - python3-libselinux
  - iptables-nft-services
debian_packages:
  - cron
  - dbus
  - gnupg
  - ifupdown
  - "{{ debian_libaio_package }}"
  - libbz2-dev
  - libgdbm-dev
  - libncurses5-dev
  - libpcre3-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libsystemd-dev
  - network-manager
  - nftables
  - python3-dev
  - python3-selinux
  - systemd
  - tk-dev
  - xz-utils
  - zlib1g-dev
  - open-iscsi
  - libffi-dev
  - libicu-dev
  - xfsprogs
ndb_kernel_args:
  - numa=off
  - transparent_hugepage=never
