common_packages:
  - acl
  - bison
  - chrony
  - curl
  - dbus
  - flex
  - gcc
  - lsof
  - lvm2
  - net-tools
  - openssh-server
  - perl
  - python3-pip
  - rsync
  - rsyslog
  - sshpass
  - tar
  - unzip
  - wget
  - zip
redhat_packages:
  - bzip2-devel
  - dbus-tools
  - gdbm-devel
  - initscripts
  - ncurses-devel
  - NetworkManager-initscripts-updown
  - openssl-devel
  - pcre-devel
  - python3-devel
  - readline-devel
  - sqlite-devel
  - systemd-devel
  - tk-devel
  - xz-devel
  - zlib-devel
  - iscsi-initiator-utils
  - firewalld
  - libffi-devel
  - libicu-devel
  - python3-libselinux
debian_packages:
  - dbus
  - libaio1
  - libbz2-dev
  - libgdbm-dev
  - libncurses5-dev
  - libpcre3-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libsystemd-dev
  - network-manager
  - python3-dev
  - tk-dev
  - xz-utils
  - zlib1g-dev
  - open-iscsi
  - ufw
  - libffi-dev
  - libicu-dev
